In [1]:
# 1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

import numpy as np
arr = np.arange(6)
print("Array:", arr)
print("Data type:", arr.dtype)

Array: [0 1 2 3 4 5]
Data type: int64


In [2]:
# 2. Given a NumPy array 'arr', check if its data type is float64.

arr = np.array([1.5, 2.6, 3.7])
arr.dtype


dtype('float64')

In [3]:
# 3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

arr = np.array([1+2j, 3+4j, 5+6j], dtype = np.complex128)
print("Array:", arr)
print("Data type:", arr.dtype)

Array: [1.+2.j 3.+4.j 5.+6.j]
Data type: complex128


In [4]:
# 4. Convert an existing NumPy array 'arr' of integers to float32 data type.

arr = np.array([1, 2, 3, 4, 5])
arr_float = arr.astype(np.float32)

print("Converted Array:", arr_float)
print("Data type:", arr_float.dtype)

Converted Array: [1. 2. 3. 4. 5.]
Data type: float32


In [5]:
# 5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

arr = np.array([1.123456789, 2.987654321, 3.141592653], dtype = np.float64)

arr_float32 = arr.astype(np.float32)

print(arr_float32)
print(arr_float32.dtype)

[1.1234568 2.9876542 3.1415927]
float32


In [6]:
# 6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.

def array_attributes(arr):
   
    if not isinstance(arr, np.ndarray):
        raise ValueError("Input must be a NumPy array")
    
    shape = arr.shape
    size = arr.size
    dtype = arr.dtype
    
    return shape, size, dtype

arr = np.array([[1, 2, 3], [4, 5, 6]])
attributes = array_attributes(arr)

print("Shape:", attributes[0])
print("Size:", attributes[1])
print("Data type:", attributes[2])

Shape: (2, 3)
Size: 6
Data type: int64


In [7]:
# 7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

def array_dimension(arr):

    if not isinstance(arr, np.ndarray):
        raise ValueError("Input must be a NumPy array")

    return arr.ndim

arr = np.array([[1, 2, 3], [4, 5, 6]])
dimension = array_dimension(arr)
print("Dimensionality:", dimension)

Dimensionality: 2


In [8]:
# 8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

def item_size_info(arr):

    if not isinstance(arr, np.ndarray):
        raise ValueError("Input must be a NumPy array")

    item_size = arr.itemsize
    total_size = arr.nbytes

    return item_size, total_size

arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
item_size, total_size = item_size_info(arr)
print("Item size (in bytes):", item_size)
print("Total size (in bytes):", total_size)

Item size (in bytes): 4
Total size (in bytes): 24


In [9]:
# 9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

def array_strides(arr):

    if not isinstance(arr, np.ndarray):
        raise ValueError("Input must be a NumPy array")

    return arr.strides

arr = np.array([[1, 2, 3], [4, 5, 6]], dtype = np.int32)
strides = array_strides(arr)
print("Strides:", strides)

Strides: (12, 4)


In [10]:
# 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

def shape_stride_relationship(arr):

    if not isinstance(arr, np.ndarray):
        raise ValueError("Input must be a NumPy array")

    return arr.shape, arr.strides

arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
shape, strides = shape_stride_relationship(arr)
print("Shape:", shape)
print("Strides:", strides)

Shape: (2, 3)
Strides: (12, 4)


In [11]:
# 11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.

def create_zeros_array(n):

    if not isinstance(n, int) or n < 0:
        raise ValueError("Input must be a non-negative integer")

    return np.zeros(n)

zeros_array = create_zeros_array(5)
print("Array of zeros:", zeros_array)
print("Shape:", zeros_array.shape)

Array of zeros: [0. 0. 0. 0. 0.]
Shape: (5,)


In [12]:
# 12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.

def create_ones_matrix(rows, cols):
    
     if not (isinstance(rows, int) and isinstance(cols, int)) or rows < 0 or cols < 0:
          raise ValueError("Rows and columns must be non-negative integers")
    
     return np.ones((rows, cols))

ones_matrix = create_ones_matrix(3, 4)
print("Matrix of ones:")
print(ones_matrix)

Matrix of ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
# 13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
# creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`.

def generate_range_array(start, stop, step):

    if not all(isinstance(i, int) for i in [start, stop, step]):
        raise ValueError("All inputs must be integers")
    if step == 0:
        raise valueError("Step must be a non-zero integer")

    return np.arange(start, stop, step)

range_array = generate_range_array(1, 10, 2)
print("Generated range array:", range_array)

Generated range array: [1 3 5 7 9]


In [14]:
# 14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
# arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).

def generate_linear_space(start, stop, num):

    if not isinstance(num, int) or num <= 0:
        raise ValueError("num must be a positive integer")
    if not isinstance(start, (int, float)) or not isinstance(stop, (int, float)):
        raise ValueError("start and stop must be numbers")

    return np.linspace(start, stop, num)

linear_space_array = generate_linear_space(0, 1, 5)
print("Generated linear space array:", linear_space_array)

Generated linear space array: [0.   0.25 0.5  0.75 1.  ]


In [15]:
# 15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.

def create_identity_matrix(n):

    if not isinstance(n, int) or n <= 0:
        raise ValueError("n must be a positive integer")

    return np.eye(n)

identity_matrix = create_identity_matrix(4)
print("Identity Matrix:", identity_matrix)

Identity Matrix: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
# 16. Write a function that takes a Python list and converts it into a NumPy array.

def list_to_numpy_array(py_list):

    if not isinstance(py_list, list):
        raise ValueError("Input must be a Python list")
        
    return np.array(py_list)

py_list = [1, 2, 3, 4, 5]
numpy_array = list_to_numpy_array(py_list)
print("Converted NumPy Array:", numpy_array)

Converted NumPy Array: [1 2 3 4 5]


In [17]:
# 17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.

original_array = np.array([1, 2, 3, 4, 5])

view_array = original_array.view()
view_array[0] = 10

print("Original Array:", original_array)
print("View Array:", view_array)

Original Array: [10  2  3  4  5]
View Array: [10  2  3  4  5]


In [18]:
# 18. Write a function that takes two NumPy arrays and concatenates them along a specified axis

def concatenate_arrays(arr1, arr2, axis = 0):

    if not isinstance(arr1, np.ndarray) or not isinstance(arr2, np.ndarray):
        raise ValueError("Both inputs must be NumPy arrays.")

    return np.concatenate((arr1, arr2), axis = axis)

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

result_axis0 = concatenate_arrays(arr1, arr2, axis = 0)
print("Concatenated along axis 0:", result_axis0)

result_axis1 = concatenate_arrays(arr1, arr2, axis = 1)
print("Concatenated along axis 1:", result_axis1)

Concatenated along axis 0: [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1: [[1 2 5 6]
 [3 4 7 8]]


In [19]:
# 19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy. concatenate`.

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8], [9, 10]])

concatenated_array = np.concatenate((arr1, arr2), axis = 1)

print("Concatenated Array:")
print(concatenated_array)

Concatenated Array:
[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


In [20]:
# 20. Write a function that vertically stacks multiple NumPy arrays given as a list.

def stack_arrays_vertically(arrays_list):

    if not all(isinstance(arr, np.ndarray) for arr in arrays_list):
        raise ValueError("All elements in the list must be NumPy arrays.")

    return np.vstack(arrays_list)

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
arr3 = np.array([[13, 14, 15], [16, 17, 18]])

arrays_list = [arr1, arr2, arr3]

stacked_array = stack_arrays_vertically(arrays_list)
print("Vertically Stack Array:")
print(stacked_array)

Vertically Stack Array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [21]:
# 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.

def create_range_array(start, stop, step):

    if step == 0:
        raise ValueError("Step size cannot be zero")

    return np.arange(start, stop + 1, step)

start = 1
stop = 10
step = 2

range_array = create_range_array(start, stop, step)
print("Range Array:", range_array)

Range Array: [1 3 5 7 9]


In [22]:
# 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

def generate_linear_space(start, stop, num):

     return np.linspace(start, stop, num)

start = 0
stop = 1
num = 10

linear_space_array = generate_linear_space(start, stop, num)
print("Equally spaced values:", linear_space_array)

Equally spaced values: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [23]:
# 23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

def create_log_spaced_array(start, stop, num):

    return np.logspace(np.log10(start), np.log10(stop), num)

start = 1
stop = 1000
num = 5

log_spaced_array = create_log_spaced_array(start, stop, num)
print("Logarithmically spaced values:", log_spaced_array)

Logarithmically spaced values: [   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [24]:
# 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.

import pandas as pd

def create_random_dataframe():

    data = np.random.randint(1, 101, size = (5, 3))

    df = pd.DataFrame(data, columns = ['Column1', 'Column2', 'Column3'])
    return df

random_dataframe = create_random_dataframe()
print(random_dataframe)

   Column1  Column2  Column3
0       88       96       51
1       60       81       85
2       36       28       27
3       91       92       84
4       50       44       46


In [25]:
# 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.

def replace_negative_with_zero(df, column_name):

    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df

data = {
    'A': [1, -2, 3, -4, 5],
    'B': [-6, 7, -8, 9, -10]
}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

modified_df = replace_negative_with_zero(df, 'A')

print("\nModified DataFrame:")
print(modified_df)

Original DataFrame:
   A   B
0  1  -6
1 -2   7
2  3  -8
3 -4   9
4  5 -10

Modified DataFrame:
   A   B
0  1  -6
1  0   7
2  3  -8
3  0   9
4  5 -10


In [26]:
# 26. Access the 3rd element from the given NumPy array.

arr = np.array([10, 20, 30, 40, 50])
print(arr[2])

30


In [27]:
# 27. Retrieve the element at index (1, 2) from the 2D NumPy array.

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(arr_2d[1, 2])

6


In [28]:
# 28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.

arr = np.array([3, 8, 2, 10, 5, 7])
print(arr[arr > 5])

[ 8 10  7]


In [29]:
# 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[2:6])

[3 4 5 6]


In [30]:
# 30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(arr_2d[0:2, 1:3])

[[2 3]
 [5 6]]


In [31]:
# 31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.

def extract_elements(arr, indices):
  
    row_indices, col_indices = zip(*indices)
    return arr[list(row_indices), list(col_indices)]

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

indices = np.array([(0, 1), (1, 2), (2, 0)]) 
result = extract_elements(arr_2d, indices)
print(result)

[2 6 7]


In [32]:
# 32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

def filter_greater_than(arr, threshold):

    return arr[arr > threshold]

arr = np.array([1, 3, 5, 7, 9])

threshold = 5
result = filter_greater_than(arr, threshold)
print(result)

[7 9]


In [33]:
# 33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.

def extract_elements_3d(array, row_indices, col_indices, depth_indices):

    if not (len(row_indices) == len(col_indices) == len(depth_indices)):
        raise ValueError("All index arrays must have the same length.")

    return array[row_indices, col_indices, depth_indices]

arr_3d = np.array([[[1,  2,  3],
                    [4,  5,  6],
                    [7,  8,  9]],
                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]],
                   [[19, 20, 21],
                    [22, 23, 24],
                    [25, 26, 27]]])

row_indices = np.array([0, 1, 2])  
col_indices = np.array([1, 2, 0])  
depth_indices = np.array([2, 1, 0]) 

result = extract_elements_3d(arr_3d, row_indices, col_indices, depth_indices)
print(result)

[ 6 17 19]


In [34]:
# 34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.

def filter_elements(arr, condition1, condition2):

    combined_condition = condition1 & condition2
    return arr[combined_condition]

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

condition1 = arr > 30
condition2 = arr < 80

result = filter_elements(arr, condition1, condition2)
print(result)

[40 50 60 70]


In [35]:
# 35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

def extract_elements(arr, row_indices, col_indices):
   
    return arr[row_indices, col_indices]

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

row_indices = np.array([0, 1, 2])  
col_indices = np.array([1, 2, 0]) 

result = extract_elements(arr_2d, row_indices, col_indices)
print(result)

[2 6 7]


In [36]:
# 36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

result = arr + 5

print(result)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [37]:
# 37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.

arr1 = np.array([[1, 2, 3]])  
arr2 = np.array([[4, 5, 6, 7],  
                 [8, 9, 10, 11],
                 [12, 13, 14, 15]])

arr1_reshaped = arr1.T
result = arr2 * arr1_reshaped

print(result)

[[ 4  5  6  7]
 [16 18 20 22]
 [36 39 42 45]]


In [38]:
# 38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

arr1 = np.array([[1, 2, 3, 4]])  
arr2 = np.array([[5, 6, 7],     
                 [8, 9, 10],
                 [11, 12, 13],
                 [14, 15, 16]])

arr1_reshaped = arr1.T 
result = arr2 + arr1_reshaped

print(result)


[[ 6  7  8]
 [10 11 12]
 [14 15 16]
 [18 19 20]]


In [39]:
# 39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

arr1 = np.array([[1], [2], [3]])
arr2 = np.array([[4, 5, 6]])

print(arr1 + arr2)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [40]:
# 40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.

arr1 = np.array([[1, 2, 3],
                [4, 5, 6]])
arr2 = np.array([[7, 8],
                [9, 10]])

arr2_reshaped = arr2[:, :, np.newaxis]

result = arr1 * arr2_reshaped
print(result)

[[[ 7 14 21]
  [32 40 48]]

 [[ 9 18 27]
  [40 50 60]]]


In [41]:
# 41. Calculate column wise mean for the given array:

arr = np.array([[1, 2, 3], [4, 5, 6]])

column_mean = np.mean(arr, axis=0)
print(column_mean)

[2.5 3.5 4.5]


In [42]:
# 42. Find maximum value in each row of the given array:

arr = np.array([[1, 2, 3], [4, 5, 6]])

max_values = np.max(arr, axis = 1)
print(max_values)

[3 6]


In [43]:
# 43. For the given array, find indices of maximum value in each column.

arr = np.array([[1, 2, 3], [4, 5, 6]])

indices = np.argmax(arr, axis = 0)
print(indices)

[1 1 1]


In [44]:
# 44. For the given array, apply custom function to calculate moving sum along rows.

arr = np.array([[1, 2, 3], [4, 5, 6]])

def moving_sum(arr, window_size):
    result = []
    for row in arr:
        row_result = []
        for i in range(len(row) - window_size + 1):
            window_sum = np.sum(row[i:i+window_size])
            row_result.append(window_sum)
        result.append(row_result)
    return np.array(result)

arr = np.array([[1, 2, 3], [4, 5, 6]])

moving_sum_result = moving_sum(arr, window_size = 2)
print(moving_sum_result)

[[ 3  5]
 [ 9 11]]


In [45]:
# 45. In the given array, check if all elements in each column are even.

arr = np.array([[2, 4, 6], [3, 5, 7]])

all_even = np.all(arr % 2 == 0, axis = 0)
print(all_even)

[False False False]


In [46]:
# 46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.

original_array = np.array([1, 2, 3, 4, 5, 6])

reshaped_matrix = original_array.reshape(2, 3)
print(reshaped_matrix)

[[1 2 3]
 [4 5 6]]


In [47]:
# 47. Create a function that takes a matrix as input and returns the flattened array.

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

def flatten_matrix(matrix):
    return matrix.flatten()

flattened_array = flatten_matrix(input_matrix)
print(flattened_array)

[1 2 3 4 5 6]


In [48]:
# 48. Write a function that concatenates two given arrays along a specified axis.

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

def concatenate_arrays(arr1, arr2, axis=0):
    
    return np.concatenate((arr1, arr2), axis = axis)

concatenated_array_axis0 = concatenate_arrays(array1, array2, axis=0)
print("Concatenated along axis 0:")
print(concatenated_array_axis0)

concatenated_array_axis1 = concatenate_arrays(array1, array2, axis=1)
print("Concatenated along axis 1:")
print(concatenated_array_axis1)

Concatenated along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1:
[[1 2 5 6]
 [3 4 7 8]]


In [49]:
# 49. Create a function that splits an array into multiple sub-arrays along a specified axis.

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

def split_array(arr, num_splits, axis = 0):

    return np.split(arr, num_splits, axis = axis)

# Split the array along axis 0 (rows) into 3 sub-arrays
split_array_axis0 = split_array(original_array, 3, axis = 0)
print("Split along axis 0 (rows):")
for sub_array in split_array_axis0:
    print(sub_array)

# Split the array along axis 1 (columns) into 3 sub-arrays
split_array_axis1 = split_array(original_array, 3, axis = 1)
print("\nSplit along axis 1 (columns):")
for sub_array in split_array_axis1:
    print(sub_array)

Split along axis 0 (rows):
[[1 2 3]]
[[4 5 6]]
[[7 8 9]]

Split along axis 1 (columns):
[[1]
 [4]
 [7]]
[[2]
 [5]
 [8]]
[[3]
 [6]
 [9]]


In [50]:
# 50. Write a function that inserts and then deletes elements from a given array at specified indices.

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

def insert_and_delete(arr, indices_to_insert, values_to_insert, indices_to_delete):

    arr = np.insert(arr, indices_to_insert, values_to_insert)
    arr = np.delete(arr, indices_to_delete)
    return arr

modified_array = insert_and_delete(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print(modified_array)

[ 1 10  4 11  5]


In [51]:
# 51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
# Perform element-wise addition between `arr1` and `arr2`.

arr1 = np.random.randint(1, 20, size = 5)
arr2 = np.arange(1, 11)[:5]
result = arr1 + arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Result of element-wise addition:", result)

arr1: [16  7  8  9 11]
arr2: [1 2 3 4 5]
Result of element-wise addition: [17  9 11 13 16]


In [52]:
# 52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers
# from 1 to 10. Subtract `arr2` from `arr1` element-wise.

arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)
result = arr1 - arr2

print("arr1:", arr1)
print("arr2", arr2)
print("Result of element-wise subtraction;", result)

arr1: [10  9  8  7  6  5  4  3  2  1]
arr2 [ 1  2  3  4  5  6  7  8  9 10]
Result of element-wise subtraction; [ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [53]:
# 53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
# Perform element-wise multiplication between `arr1` and `arr2`.

arr1 = np.random.randint(1, 20, size = 5)
arr2 = np.arange(1, 6)
result = arr1 * arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Result of element-wise multiplication:", result)

arr1: [13 13 15  4 10]
arr2: [1 2 3 4 5]
Result of element-wise multiplication: [13 26 45 16 50]


In [54]:
# 54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1
# to 5. Perform element-wise division of `arr1` by `arr2`.

arr1 = np.arange(2, 11, 2)
arr2 = np.arange(1, 6)
result = arr1 / arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Result of element-wise division:", result)

arr1: [ 2  4  6  8 10]
arr2: [1 2 3 4 5]
Result of element-wise division: [2. 2. 2. 2. 2.]


In [55]:
# 55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
# reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

arr1 = np.arange(1, 6)
arr2 = arr1[::-1]
result = arr1 ** arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Result of element-wise exponentiation:", result)

arr1: [1 2 3 4 5]
arr2: [5 4 3 2 1]
Result of element-wise exponentiation: [ 1 16 27 16  5]


In [56]:
# 56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

def count_substring(arr, substring):

    return np.sum(np.char.find(arr, substring) != -1)

substring = 'hello'

count = count_substring(arr, substring)
print(f"The substring 'substring' occurs {count} times.")

The substring 'substring' occurs 3 times.


In [57]:
# 57. Write a function that extracts uppercase characters from a NumPy array of strings.

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

def extract_uppercase(arr):

    return np.array([''.join([char for char in string if char.isupper()]) for string in arr])

print("Uppercase characters:", extract_uppercase(arr))

Uppercase characters: ['H' 'W' 'OAI' 'GPT']


In [58]:
# 58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

def replace_substring(arr, old_substring, new_substring):

    return np.char.replace(arr, old_substring, new_substring)

old_substring = 'apple'
new_substring = 'fruit'

modified_array = replace_substring(arr, old_substring, new_substring)
print("Modified array:", modified_array)

Modified array: ['fruit' 'banana' 'grape' 'pinefruit']


In [59]:
# 59. Write a function that concatenates strings in a NumPy array element-wise.

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

def concatenate_strings(arr1, arr2):

    return np.char.add(arr1, arr2)

concatenated_array = concatenate_strings(arr1, arr2)
print("Concatenated array:", concatenated_array)

Concatenated array: ['HelloOpen' 'WorldAI']


In [60]:
# 60. Write a function that finds the length of the longest string in a NumPy array.

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

def longest_string_length(arr):
    
    lengths = np.char.str_len(arr)
    return np.max(lengths)

longest_length = longest_string_length(arr)
print("Length of the longest string:", longest_length)

Length of the longest string: 9


In [61]:
# 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
# standard deviation of the dataset using NumPy's functions.

dataset = np.random.randint(1, 1001, size = 100)

mean = np.mean(dataset)
median = np.median(dataset)
variance = np.var(dataset)
std_deviation = np.std(dataset)

print(f"Mean: {mean}")
print(f"Median: {median}")
print(f"Variance: {variance}")
print(f"Standard Deviation: {std_deviation}")

Mean: 473.06
Median: 431.5
Variance: 83582.95640000001
Standard Deviation: 289.10717113209074


In [62]:
# 62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

dataset = np.random.randint(1, 101, size = 50)

percentile_25 = np.percentile(dataset, 25)
percentile_75 = np.percentile(dataset, 75)

print(f"25th Percentile: {percentile_25}")
print(f"75th Percentile: {percentile_75}")

25th Percentile: 34.0
75th Percentile: 80.0


In [63]:
# 63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.

array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([5, 4, 3, 2, 1])

correlation_matrix = np.corrcoef(array1, array2)
correlation_coefficient = correlation_matrix[0, 1]

print(f"Correlation coefficient: {correlation_coefficient}")

Correlation coefficient: -0.9999999999999999


In [64]:
# 64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

result = np.dot(matrix1, matrix2)

print("Matrix multiplication result:")
print(result)

Matrix multiplication result:
[[19 22]
 [43 50]]


In [65]:
# 65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.

array = np.random.randint(10, 1001, size = 50)

percentile_10 = np.percentile(array, 10)
percentile_50 = np.percentile(array, 50)
percentile_90 = np.percentile(array, 90)

first_quartile = np.percentile(array, 25)
third_quartile = np.percentile(array, 75)

print(f"10th Percentile: {percentile_10}")
print(f"50th Percentile (Median): {percentile_50}")
print(f"90th Percentile: {percentile_90}")
print(f"First Quartile (25th Percentile): {first_quartile}")
print(f"Third Quartile (75th Percentile): {third_quartile}")

10th Percentile: 80.6
50th Percentile (Median): 497.0
90th Percentile: 936.8000000000001
First Quartile (25th Percentile): 321.0
Third Quartile (75th Percentile): 730.5


In [66]:
# 66. Create a NumPy array of integers and find the index of a specific element.

arr = np.array([10, 20, 30, 40, 50])

element = 30
index = np.where(arr == element)[0]

if index.size > 0:
    print(f"The index of the element {element} is: {index[0]}")
else:
    print(f"The element {element} is not in the array.")

The index of the element 30 is: 2


In [67]:
# 67. Generate a random NumPy array and sort it in ascending order.

random_array = np.random.randint(1, 100, size = 10)
sorted_array = np.sort(random_array)

print("Original random array:", random_array)
print("Sorted array:", sorted_array)

Original random array: [46 52 69 54 21 54 81 33 41  4]
Sorted array: [ 4 21 33 41 46 52 54 54 69 81]


In [68]:
# 68. Filter elements >20  in the given NumPy array.

arr = np.array([12, 25, 6, 42, 8, 30])
filtered_elements = arr[arr > 20]

print("Filtered elements (greater than 20):", filtered_elements)

Filtered elements (greater than 20): [25 42 30]


In [69]:
# 69. Filter elements which are divisible by 3 from a given NumPy array.

arr = np.array([1, 5, 8, 12, 15])
divisible_by_3 = arr[arr % 3 == 0]

print("Elements divisible by 3:", divisible_by_3)

Elements divisible by 3: [12 15]


In [70]:
# 70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.

arr = np.array([10, 20, 30, 40, 50])
filtered_elements = arr[(arr >= 20) & (arr <= 40)]

print("Filtered elements (>= 20 and <= 40):", filtered_elements)

Filtered elements (>= 20 and <= 40): [20 30 40]


In [71]:
# 71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.

arr = np.array([1, 2, 3])

byte_order = arr.dtype.byteorder

if byte_order == "=":
    print("The byte order is native to the system.")
elif byte_order == "<":
    print("The byte order is little-endian.")
elif byte_order == ">":
    print("The byte order is big-endian.")
else:
    print("Unknown byte order.")

print(f"Raw byte order code: {byte_order}")

The byte order is native to the system.
Raw byte order code: =


In [72]:
# 72. For the given NumPy array, perform byte swapping in place using `byteswap()`.

arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap(inplace = True)

print("Array after byte swapping:", arr)

Array after byte swapping: [16777216 33554432 50331648]


In [73]:
# 73. For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.

arr = np.array([1, 2, 3], dtype=np.int32)
swapped_arr = arr.view(arr.dtype.newbyteorder())

print("Swapped byte order array:", swapped_arr)

Swapped byte order array: [16777216 33554432 50331648]


In [74]:
# 74. For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.

arr = np.array([1, 2, 3], dtype=np.int32)

import sys 

system_endian = sys.byteorder

if system_endian == 'little':
    swapped_arr = arr.view(arr.dtype.newbyteorder('>'))
else:
    swapped_arr = arr.view(arr.dtype.newbyteorder('<'))

print('Swapped byte order array:', swapped_arr)

Swapped byte order array: [16777216 33554432 50331648]


In [75]:
# 75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.

arr = np.array([1, 2, 3], dtype=np.int32)

system_endian = sys.byteorder
array_endian = arr.dtype.byteorder

if array_endian == '=':
    print("The array is in the system's native byte order. No byte swapping needed.")
elif (array_endian == '<' and system_endian == 'big') or (array_endian == '>' and system_endian == 'little'):
    print("Byte swapping is necessary.")
else:
    print("The array is already in the correct byte order for this system.")

The array is in the system's native byte order. No byte swapping needed.


In [76]:
# 76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify
# an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

arr1 = np.arange(1, 11)
copy_arr = arr1.copy()
copy_arr[0] = 100

print("arr1:", arr1)
print("copy_arr:", copy_arr)

arr1: [ 1  2  3  4  5  6  7  8  9 10]
copy_arr: [100   2   3   4   5   6   7   8   9  10]


In [77]:
# 77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
# the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

matrix = np.random.randint(1, 10, size=(3, 3))
view_slice = matrix[1:, 1:]
view_slice[0, 0] = 90

print("Original matrix:")
print(matrix)
print("\nModified view_slice")
print(view_slice)

Original matrix:
[[ 7  5  4]
 [ 3 90  7]
 [ 3  6  8]]

Modified view_slice
[[90  7]
 [ 6  8]]


In [78]:
# 78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
# `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

array_a = np.arange(1, 13).reshape(4, 3)
view_b = array_a[1:, 1:]
view_b += 5

print("Original array_a:")
print(array_a)
print("\nModified view_b:")
print(view_b)

Original array_a:
[[ 1  2  3]
 [ 4 10 11]
 [ 7 13 14]
 [10 16 17]]

Modified view_b:
[[10 11]
 [13 14]
 [16 17]]


In [79]:
# 79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view
# `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it
# reflects changes in the original `orig_array`.

orig_array = np.arange(1, 9).reshape(2, 4)
reshaped_view = orig_array.reshape(4, 2)
reshaped_view[0, 0] = 99

print("Original array:")
print(orig_array)
print("\nReshaped view:")
print(reshaped_view)

Original array:
[[99  2  3  4]
 [ 5  6  7  8]]

Reshaped view:
[[99  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]]


In [80]:
# 80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
# elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data

data = np.random.randint(1, 10, size=(3, 4))
data_copy = data[data > 5].copy()
data_copy[0] = 90

print('Original data:')
print(data)
print("\nModified data_copy:")
print(data_copy)

Original data:
[[5 5 1 3]
 [6 4 4 3]
 [4 5 4 5]]

Modified data_copy:
[90]


In [81]:
# 81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

A = np.random.randint(1, 10, size = (3, 3))
B = np.random.randint(1, 10, size = (3, 3))

addition_result = A + B
subtraction_result = A - B

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)

print('\nAdddition of A and B:')
print(addition_result)
print("\nSubtraction of A and B:")
print(subtraction_result)

Matrix A:
[[9 2 8]
 [9 8 6]
 [7 5 3]]

Matrix B:
[[4 6 2]
 [2 5 8]
 [9 3 5]]

Adddition of A and B:
[[13  8 10]
 [11 13 14]
 [16  8  8]]

Subtraction of A and B:
[[ 5 -4  6]
 [ 7  3 -2]
 [-2  2 -2]]


In [82]:
# 82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

C = np.random.randint(1, 10, size = (3, 2))
D = np.random.randint(1, 10, size = (2, 4))

result = C @ D

print("Matrix C (3x2):")
print(C)
print("\nMatrix D (2x4):")
print(D)
print("\nMatrix multiplication result (3x4):")
print(result)

Matrix C (3x2):
[[6 7]
 [7 2]
 [9 9]]

Matrix D (2x4):
[[7 3 6 3]
 [6 1 6 9]]

Matrix multiplication result (3x4):
[[ 84  25  78  81]
 [ 61  23  54  39]
 [117  36 108 108]]


In [83]:
# 83. Create a matrix `E` and find its transpose.

E = np.random.randint(1, 10, size = (3, 4))
E_transpose = E.T

print("Matrix E (3x4):")
print(E)
print("\nTranspose of E (4x3):")
print(E_transpose)

Matrix E (3x4):
[[2 5 8 2]
 [5 3 1 3]
 [6 2 7 6]]

Transpose of E (4x3):
[[2 5 6]
 [5 3 2]
 [8 1 7]
 [2 3 6]]


In [84]:
# 84. Generate a square matrix `F` and compute its determinant.

F = np.random.randint(1, 10, size = (3, 3))
det_F = np.linalg.det(F)

print("Matrix F (3x3):")
print(F)
print("\nDeterminate of F:")
print(det_F)

Matrix F (3x3):
[[7 2 4]
 [2 2 4]
 [1 8 3]]

Determinate of F:
-129.99999999999997


In [85]:
# 85. Create a square matrix `G` and find its inverse.

G = np.random.randint(1, 10, size = (3, 3))
det_G = np.linalg.det(G)

if det_G != 0:
    G_inverse = np.linalg.inv(G)
    print("Matrix G (3x3):")
    print(G)

    print("\nInverse of G:")
    print(G_inverse)
else:
    print("Matrix G is singular and cannot be inverted.")

Matrix G (3x3):
[[1 2 9]
 [8 6 9]
 [2 9 7]]

Inverse of G:
[[-0.09176471  0.15764706 -0.08470588]
 [-0.08941176 -0.02588235  0.14823529]
 [ 0.14117647 -0.01176471 -0.02352941]]
